// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAc5dB5Kzh-OHNLVvi_MoFH4CeM5pZiVOs',
    appId: '1:343549642785:web:71e512f1ae33cbaf783b60',
    messagingSenderId: '343549642785',
    projectId: 'ecommerce-40aab',
    authDomain: 'ecommerce-40aab.firebaseapp.com',
    storageBucket: 'ecommerce-40aab.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBo3iSqx_mUE4woaTqg2N5DVEuZ9S52n5I',
    appId: '1:343549642785:android:ea5ab9c6ad68dc09783b60',
    messagingSenderId: '343549642785',
    projectId: 'ecommerce-40aab',
    storageBucket: 'ecommerce-40aab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAycGG12PisAZYaDehShvIvDVYlfDHLykw',
    appId: '1:343549642785:ios:8bfe9aee1c49d795783b60',
    messagingSenderId: '343549642785',
    projectId: 'ecommerce-40aab',
    storageBucket: 'ecommerce-40aab.appspot.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAycGG12PisAZYaDehShvIvDVYlfDHLykw',
    appId: '1:343549642785:ios:8bfe9aee1c49d795783b60',
    messagingSenderId: '343549642785',
    projectId: 'ecommerce-40aab',
    storageBucket: 'ecommerce-40aab.appspot.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAc5dB5Kzh-OHNLVvi_MoFH4CeM5pZiVOs',
    appId: '1:343549642785:web:2b12e05550402446783b60',
    messagingSenderId: '343549642785',
    projectId: 'ecommerce-40aab',
    authDomain: 'ecommerce-40aab.firebaseapp.com',
    storageBucket: 'ecommerce-40aab.appspot.com',
  );

}